import numpy as np
import pandas as pd

df=pd.read_csv("/Users/ashwini/All_CSV_files/tips.csv")
print(df.head())
print(80*'*')
print('sorted values:\n',df.sort_values('tip'))
print(80*'*')
print('sorted values:\n',df.sort_values('tip',ascending=True))
print(80*'*')
print('sorted values:\n',df.sort_values('tip',ascending=False))
print(80*'*')
print('sorted values:\n',df.sort_values(['tip','size']))
print(80*'*')
print('max value:',df['total_bill'].max())
print(80*'*')
print('max element index:',df['total_bill'].idxmax())
print(80*'*')
print('min value:',df['total_bill'].min())
print(80*'*')
print('min element index:',df['total_bill'].idxmin())
print(80*'*')
#print('correlation:',df.corr())
print('Same value counts:',df['sex'].value_counts)
print(80*'*')
print('Unique values:',df['sex'].nunique())
print(80*'*')
print('Replacing values Female to F:',df['sex'].replace('Female','F'))
print(80*'*')
print('Replacing values Female to F:',df['sex'].replace(['Female','Male'],['F','M']))
print(80*'*')

mymap={'Female':'F','Male':'M'}
print(df['sex'].map(mymap))
print(80*'*')
print(df.duplicated())
print(80*'*')
print(df['total_bill'].between(10,20))
print(80*'*')
print(df.nlargest(10,'tip'))
print(80*'*')
print(df.sample(5))